name: Python Package Test

on:
  push:
    branches:
      - ${{ env.BRANCH_NAME }}
  pull_request:
    branches:
      - ${{ env.BRANCH_NAME }}

env:
  PYTHON_VERSION: '3.12'
  ENV_NAME: 'testenv312'
  REQUIREMENTS_FILE: 'requirements.txt'
  ENVIRONMENT_FILE: 'environment.yml'
  BRANCH_NAME: 'master'

jobs:
  test:
    runs-on: self-hosted   # ここで self-hosted を指定

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f ${{ env.REQUIREMENTS_FILE }} ]; then pip install -r ${{ env.REQUIREMENTS_FILE }}; fi
          if [ -f ${{ env.ENVIRONMENT_FILE }} ]; then conda env create -f ${{ env.ENVIRONMENT_FILE }}; fi
          conda activate ${{ env.ENV_NAME }}

      - name: Run tests
        run: |
          pytest --cov=sample tests/
